name: Docker

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Trust-DNS version
        id: check
        run: |
          echo "trust_dns_version=$(jq -r '.max_stable_version' ./latest-release.json)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            TRUST_DNS_VERSION=${{ steps.check.outputs.trust_dns_version }}
          tags: |
            mickare/trust-dns:${{ steps.check.outputs.trust_dns_version }} 
            ghcr.io/${{github.repository}}:${{ steps.check.outputs.trust_dns_version }}
          push: ${{ github.ref == 'refs/heads/main' }}
          labels: |
            "org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
